services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-container
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:stable-alpine3.17-perl
    container_name: nginx-container
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: db_container
    image: mysql:latest
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  mailhog:
    container_name: mailhog_container
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"

  cron:
    container_name: cron_container
    build: ./cron
    volumes:
      - ../src:/var/www
      - ./log/cron:/var/log/cron